runtime: nodejs8
api_version: 1

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build

- url: /favicon\.ico
  static_files: build/assets/favicon.png
  upload: build/assets/favicon.png