apiVersion: v1
kind: Deployment
metadata:
  name: my-site
  labels:
    k8s-app: default-http-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    containers:
    - name: default-http-backend
      image: edwardrowens/mysite:latest
      ports:
      - containerPort: 8000